{
 "title": "engine-camunda-dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "timeRate",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 15, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "cpu" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "system_cpu_usage" }
   ]
  },
  {
   "title": "Memória",
   "type": "stat",
   "gridPos": { "h": 15, "w": 7, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{area=\"heap\",id=\"G1 Eden Space\"} ",
     "legendFormat": "engine-camunda"
    }
   ]
  },
  {
   "title": "Logs de erro",
   "type": "stat",
   "gridPos": { "h": 15, "w": 6, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (application,level)(logback_events_total{level=\"error\"})\r\n\r\n\r\n\r\n\r\n\r\n\r\n    "
    }
   ]
  }
 ]
}